package tn.pi.back.model;

public enum Specialite {
    CARDIOLOGIE,
    DERMATOLOGIE,
    ENDOCRINOLOGIE,
    GASTROENTEROLOGIE,
    GYNECOLOGIE,
    MEDECINE_GENERALE,
    NEUROLOGIE,
    ONCOLOGIE,
    OPHTALMOLOGIE,
    ORTHOPEDIE,
    PEDIATRIE,
    PSYCHIATRIE,
    PNEUMOLOGIE,
    RHUMATOLOGIE,
    UROLOGIE
}

